[package]
name = "sushi-rs-dioxus-example"
version = "0.1.0"
edition = "2024"

[dependencies]
dioxus = { version = "0.7.10", features = ["web"] }
sushi-rs = { path = "../../", features = ["dio"] }
dioxus-logger = { version = "0.7.10" }

[profile]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
